- name: Check if zabbix-agent is installed
  command: dpkg-query -W zabbix-agent
  register: package_check_deb
  failed_when: package_check_deb.rc > 1
  changed_when: package_check_deb.rc == 1

- name: Download zabbix-release_3.2-1+trusty_all.deb
  get_url: 
    url="{{ zabbix_ubuntu_trusty_url }}"
    dest="/tmp/{{ zabbix_ubuntu_trusty_pkg }}.deb"
  when: package_check_deb.rc == 1 and ansible_distribution_release == "trusty"

- name: Download zabbix-release_3.2-1+xenial_all.deb
  get_url: 
    url="{{ zabbix_ubuntu_xenial_url }}"
    dest="/tmp/{{ zabbix_ubuntu_xenial_pkg }}.deb"
  when: package_check_deb.rc == 1 and ansible_distribution_release == "xenial"

- name: Install zabbix zabbix-release_3.2-1+trusty_all.deb
  apt: deb="/tmp/{{ zabbix_ubuntu_trusty_pkg }}.deb"
  sudo: true
  when: package_check_deb.rc == 1 and ansible_distribution_release == "trusty"

- name: Install zabbix zabbix-release_3.2-1+xenial_all.deb
  apt: deb="/tmp/{{ zabbix_ubuntu_xenial_pkg }}.deb"
  sudo: true
  when: package_check_deb.rc == 1 and ansible_distribution_release == "xenial"

- name: Install zabbix agent on Ubuntu 14.04 LTS (trusty)
  apt: pkg=zabbix-agent state=present  update_cache=yes
  when: package_check_deb.rc == 1 and ansible_distribution_release == "trusty"

- name: install zabbix agent on Ubuntu 16.04 LTS (xenial)
  apt: pkg=zabbix-agent state=present update_cache=yes
  when: package_check_deb.rc == 1 and ansible_distribution_release == "xenial"

- name: Uncompression ef-zabbix-scripts.tar.gz
  unarchive: src=ef-zabbix-scripts.tar.gz dest=/tmp

- name: copy  zabbix agent configure file
  template: src=ef_zabbix/zabbix_agentd.conf  dest=/etc/zabbix/zabbix_agentd.conf  owner=zabbix group=zabbix mode=644 backup=yes

- name: copy zabbix cron job file
  template: src=ef_zabbix/zabbix_cronjob dest=/etc/cron.d/zabbix_cronjob  owner=zabbix group=zabbix mode=644

- name: copy zabbix sudo file
  template: src=ef_zabbix/zabbix  dest=/etc/sudoers.d/zabbix  owner=root group=root mode=644

- name: Setup zabbix  agent file hostname
  replace:
    dest=/etc/zabbix/zabbix_agentd.conf
    regexp='# Hostname='
    replace="Hostname={{inventory_hostname}}"
    #backup=yes

- name: Setup zabbix agent Active mode
  replace:
    dest=/etc/zabbix/zabbix_agentd.conf
    regexp='# ServerActive='
    replace="ServerActive=127.0.0.1"
    #backup=yes
  #when: package_check_deb.rc == 1 and ansible_distribution_release == "xenial"

- name: start zabbix service
  shell: /etc/init.d/zabbix-agent restart

- name: restart crond 
  shell: /etc/init.d/cron restart

